<!DOCTYPE html>
<html>

  <!-- **************************  Head ***************************** -->
  <head>
    <meta charset="utf-8"/>
    <title>GOES Getter</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="style.css" media="screen" />
  </head>

  <!-- **************************  Body ***************************** -->
  <body>
      <h1>GOES Getter</h1>
      <div>Give me data or give me death</div>

      <?php echo $foo ?>
  </body>

</html>
