version: '2'

services:
  mongodb:
    build: ./mongodb
    image: goesgetter/mongodb
    container_name: mongodb
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - /srv/goes/db:/data/db
    environment:
      - MONGODB_PASS=password
      - MONGODB_USER=goes
      - MONGODB_DATABASE=goes
  goeslim:
    build: ./goeslim
    image: rustyeddy/goeslim
    container_name: goeslim
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/rusty/src/goes/goeslim:/srv/www
      - /srv/goes/data:/srv/goes/data
    links:
      - mongodb
