# Makefile
init: 
	echo "Need to make getter"
	./init.sh

build: docker-compose.yml 
	docker-compose build

up:
run:
	docker-compose up

stop:
down:
	docker-compose down

shell:
	docker-compose exec getter bash
