#!/bin/bash

##
## We need at least one command line argument for the site name
## 
if [ $# -lt 1 ]; then
	echo "You need to tell the name of your site!, bye..."
	exit 4
fi	
site=$1

##
## TODO: Allow this stuff to be read from a .json config file
##
if [ ! -e "config.sh" ]; then
	echo "Please create a config.sh file, refer to config-sample.sh for details"
	exit 1
fi	

source config.sh

##
## Check to make sure we have wp installed
##
command -v wp >/dev/null 2>&1 || { echo >&2 "We need wp (wp-cli) to run, but I can't find it! bye.."; exit 3; }

#########################################################################
# Now start doing the damage.
#########################################################################

##
## TODO: check to make sure the directory does not already exist before
## trying to make it, although I guess this does not really matter...
##
if [ -e $sitedir ]; then
	echo "$sitedir already exists. I ain't gonna overwrite it!, bye..."
	exit 2
fi

mkdir $sitedir
cd $sitedir

##
## TODO: check to see if there are already files here and prompt to clobber
##

# Download WP
wp core download

# create the config file
wp core config --dbname=${dbname} --dbuser=${dbuser} --dbpass=${dbpasswd}

##
## Create the dabase.
##
## TODO: Check to see if the DB already exists, if so give the user a chance to clobber
##
wp db create

##
## Actually do the install.
##
## TODO: Fix the site title it is broken!
##
wp core install --url=${siteurl} --title=$${sitetitle} --admin_user=${admin_user} \
	--admin_password=${admin_password} --admin_email=${admin_email}

## Install and activate the desktop server plugin
wp plugin install desktopserver --activate

##
## Now create the vhost file and restart apache
##
sudo ./vhost ${site}.conf $siteurl $admin_email $sitedir

